version: '2'

services:

  base:
    build:
      context: .
    image: 'developmentseed/sat-fetch:latest'
    #env_file: .env
    entrypoint: /bin/bash
    volumes:
      - '.:/home/geolambda/work'

  test:
    image: 'developmentseed/sat-fetch:latest'
    entrypoint: bash -c 'pytest -v test/'
    working_dir: /home/geolambda
    #env_file: .env
    volumes:
      - './test:/home/geolambda/test'
